asf: update to commit 9580a62
New commits imported:
9580a62 asf_ipsec: Patch to fix the compilation error.
e7a1828 Merge pull request #84 in SDK/asf from ~B49015/asf:sdk_1.9_master to sdk_1.9_master
eee4467 DEBUG: compilation error fixed when ASF_IPSEC_DEBUF flag is enabled.
71db029 asf_tcp: Patch to correct tcp timestamp type.
f8e3df0 IPSEC: Fixed for stack dump on running fragmented ping traffic
c63ffa5 asfipsec: Patch to fix iph issue in non-proto offload case.
7170610 asfipsec: Patch to decrement buffer count of all frag in red off case
f5cd876 asfipsec: Patch to fix inSA offload in NAT-T case.
d455e70 Makefile: use KBUILD_OUTPUT to point to build-artifacts
be19cd0 asf_frag: Patch to fix crash on mtu change.
0f88dae asf_ipv6_frag: Patch to fix ipv6 UDP frag and ping6 forwarding issue.
8c3f4bc ipsecfp.h: Patch to add support of SHA2-384 and SHA2-512
03bd11a ipsecfp.c: Patch to fix crash in ipsec in full mode.
e2213ef ipsec ctrl - correction in container index check
33e0fd4 ipsec - ah - fix the fragmentation case for dpbp check
f5f542d asf - return packets to linux on interface not found
1c7241e asfipsec - 64 bit support Signed-off-by: Hemant Agrawal <Hemant@freescale.com>
879b161 asfctrl - using ASF defined number of interfaces
83b6181 IPSEC: Crash fixed in case of revalidation
1b26690 ASF_REASM_DEBUG: Fix for compilation error when ASF_REASM_DEBUG is enabled
74a5953 ASF_DEBUG: Improving prints for ASF Debugging
eee54a3 asf icmp reply support for DF flag
10e3bf8 asfipsec - error checks, debug prints and error handling corrections
c47696c ipsec - lock, unlikely, null checks
5d26d9f ipsec- meaningfull caam error prints
834f88a asfipsec-ah- correction in ah shared desc direction
88edb32 asf_ipsec: adds the support for SHA2 algorithms in AH.
ca8c486 ASFIPSEC: While deleting container properly freeing the pSASPDMapNode in SA
c2c81cc ASF_IPSEC: Wrong counter being incremented. When OuSA is not found
32cea7f ASFIPSEC: Patch to avoid looping in case of rekeying on running traffic.
239c317 ASF_IPSEC: Adding local_bh_enable() in error case. CQ:ENGR00336981 Signed-off-by: Sridhar Pothuganti <sridhar.pothuganti@freescale.com> Change-Id: If72f7135fe5e294a51f0c582bdbd56ca3c78f844 Reviewed-on: http://git.am.freescale.net:8181/24207 Reviewed-by: Nikhil Agarwal <Nikhil.Agarwal@freescale.com> Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com> Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>
42837b8 ASF_IPSEC_AH: ASFSkbFree is not happening for DPAA/QMAN based platforms in some error cases as the free is under check. Correcting this. CQ:ENGR00336981 Signed-off-by: Sridhar Pothuganti <sridhar.pothuganti@freescale.com> Change-Id: Iaf847710cf583ff4d7e708013af77f522027e2eb Reviewed-on: http://git.am.freescale.net:8181/24208 Reviewed-by: Arun Pathak <arun.pathak@freescale.com> Reviewed-by: Sandeep Malik <Sandeep.Malik@freescale.com> Tested-by: Sandeep Malik <Sandeep.Malik@freescale.com>
e0410f9 ASFIPSEC: [sswan] Fix for issues with Child SA re-negotiation.
e52f3c5 ASFIPSEC: Patch to fix flow re-validation issue.
b99fb26 ASF_IPSEC: Freeing the skb in case of ICV comparion failed for AH
163ed89 asf: Patch to fix ping6 fragmentation issue.
48220d7 asf: Patch to fix skb data pointer and other frag issue.
2ff46e7 ASF for DPAA integrated with Linux QoS module
a7d1981 asf-disabling qos compilation for dpaa platforms
8bcee43 ipsec-changing multi-policy sa support to be compile time
580a4f7 ipsecproc: Patch to fix display of ipsec stats.
955d26f asfctrl: Patch to fix error print when vlan i/f is removed.
44a5110 asf_fmc: Patch to update the name of xml files.
9f67f3f asf: Patch to fix ipv6 issue on dpaa.
fac492d asf: Patch to return jumbo packet back
6b3d862 Removing Ethernet padding in abuf to skb conversion
db49a6b Aligning function ASFFFPProcessAndSendFD and ASFFFPProcessAndSendPkt while validating flows
6b5e75d ASFIPSEC: Patch to fix issues of order conversion while code review.
1c80cd5 Klocwork_LS1021_ASF: Fixing klocwork issues.
6a4a834 ASF ARM Porting: Using ASF network order and host order macros.
e60d41c asfipsec: Patch to fix crash in running traffic when ipsec script is run.
b682589 Adding HARD_TX_LOCK while doing dev hard xmit.
da26fbd ASFIPSEC: Fix for out_sa stats not incremented in IPv6
3a41ff1 ASFQOS: Crash on configuring DRR QDisc after flushing out DRR Qdisc first time.
04fd26d ASFIPSEC: Patch to fix ICV error due to cache cohorency issue.
26b8f9d ASFIPSEC: Porting ASFIPSEC to LS1021
80d1153 ASFIPSEC: Flushing ah-sha1 policy at high rate
982d542 Firewall rules don't work if applied, before flows get offloaded.
a7a2fee ASF_FW/NAT: SCP is not working when SNAT [IPv4/IPv6] is enabled on the DUT.
9d2ed93 Applying Firewall rule in running traffic gives CRASH.
426aefa ASFIPSEC: Getting crash while testing for IPv6-in-IPv6 ESP with TCP protocol.
d3843de ASFIPSEC: Crash on making interface down.
ae72e06 ASF IPv6 Firewall: Sending high rate traffic in the
e19c45e ASF ARM Porting: While forwarding if we down Egress interface, we get crash.
c01729e ASF ARM Porting: Cannot remove configured VLan
0ac82ad ASFIPSEC: Porting IPSEC AH to LS1021A (arm based).
38671c3 ASF ARM porting: IPv6 Fragmentation
fb2ca85 ASF ARM porting: IPv4 Fragmentation
471a4b2 ASF ARM porting: IPv6 forwarding with TCP/UDP header.
4d443a1 ASF ARM Porting: Removing compilation error of ASF without rx tx patch in linux.
aa33f01 ASF ARM porting: IPv4 forwarding with UDP/TCP header.
f5a8705 ASF ARM porting: Defining order conversion macros.
3f76910 ASF ARM porting: Setting ARCH=$(ARCH) in Makefile
d5dabe7 ASF: Removing compilation error because of updation in linux structure 'dpa_priv_s'.
01cd004 asf: Patch to fix crash in case of ipsec at high rate traffic.
66fe758 asfipsec_ah: Patch to fix sha256 in case of AH only.
a81d920 asf: Patch to fix wrong port no assigned in ipsec flow.
8ebb93b asf: Patch to handle ipv6 traffic in case of seqno overflow.
fcd0843 asf: Patch to fix sha256 issue.
7467249 Crash observed with AH-ONLY-SHA384
9e37dc8 asf: Patch to fix some klockwork issue.
e1b2a12 ASFIPSEC: Adding support for handling IPv6 in IPv4 and IPv4 in IPv6 case in QMAN SEC4x
3c05ad1 ASFIPSEC: TOS is not correctly copied in IPv4 in IPv6 case
6363e0b Solution to Fragmented packets are not getting through AH tunnel
5a96807 asf: Patch to fix tail pointer-offset issue in 64-bit machine.
26375d3 ASFIPSEC: Solving problem in secfp_inCompleteCheckAndTrimPkt code
bdb17ab ASFIPSEC: Solving case of infinite loop in secfp_qman_out_submit
13dc5a9 ASFIPSEC: Freeing correct sgt pointer in espDQRRCallback
ca75bf9 ASFIPSEC: Incrementing pSG->len by ulFragPadlen in secfp_qman_in_submit
a58ba45 ASFIPSEC: struct addr in scatter_gather_entry_t is changed.
81d797b ASFIPSEC: Linearising frag_list or nr_frags coming from Linux
9458153 asf: Patch to remove conflict of skb cb field b/w reasm and ipsec.
4d3993b Solution to ESP IP pakcet more than interface MTU going out
1175536 ASFIPSEC: Handling seq number overflow in espDQRRCallback
b5fb8fc ASF: Removing compilation error after adding patch: "ASFFFP adding support for PPP-IPV6 traffic"
4018106 ASFFFP - adding support for PPP-IPV6 traffic
b26d25f asf_klockwork: Patch to fix issue reported by klockwork
36ffe84 ASFIPSEC: Fix for crash seen on T4240 in case of ping
ef4a7a1 asf_compilation: Patch to remove the compilation warnings.
3f7d40c secfp_finishOffloadOutPacket: corrected the SPD index value l2blob refresh
837a5f9 ASFIPSEC_AH: Fix for crash seen on T4240 in AH only case
745a912 ASFIPSEC: Fixing miscellaneous error
1cdde18 asfIpv4Fragment was not copying the IP options in fragmented packets.
62b1311 asfIpv4Defrag IP header length corruption solved
c7c8ba3 ASF fragmentation: Buffer freed in case of VLAN parent device  not found
2c478eb asf_free_buf_skb function was not considering the frag_lsit while releasing the buffer to BMan. asf_free_buf_skb is also called, in error case, after ip reassemmbly. In that case the buffers are leaked.
d0572b1 ASFIPSEC: Removing compilation errors.
ee1e3e8 ASF_IPSEC: Fix for SA leak(Orphaned SA wothout Container)
b2ac65f asf_ipsec: Patch to add the support for AH in Sec 3.x
44cb2b0 asf_reasm: Patch to fix the processing for re-asm.
99f89ed asf_ipsec: Patch for multi-policy single SA additional cases.
a6cb24c ASF-IPSEC:SA flush with traffic through the DUT causing crash.
fd7f119 ASFCTRL: Out SA is not getting offloaded if SA and then policy is configured.
93eb52b TC/TOS in inner header is not getting copied to TOS/TC of outer header respectively.
0fc4363 asf: Resolve fragmentation issue in case of red-off ipsec.
2ed8b33 ASF: Patch to fix hop-limit/ttl decrement in asf IPSec module.
d6cc5b5 ASFREASM: Patch to fix the crash in case cb not found.
aef3564 asf_ipsec_ah: Patch to fix the issue of ping6 not working.
5a82c4d ASFIPSEC: Use correct length in descriptor while using dpovrd for multiple policy.
f305c67 asf_ipsec: Patch to fix the ICV errors in case of ESN.
9b5ae90 asf_ipsec: Patch to fix the crash seen in case of AH IPsec.
ae85d24 ASFIPSEC: Trim correct fragment after decrypting packet.
8d2c11c ASFIPSEC_AH: Search AH table to find SA in case of dropping packet.
d83a4d5 ASFIPSEC: Changing the block size of AES-CTR.
a37f009 ASFIPSEC: Added des/3des-xcbc support.
38259f6 asf_ipsec: Patch for ICV errors seen in case of SHA256.
07e2c90 ASFIPSEC: Fix for ASF-IPSec to run with SA first then policy configuration.
62844a7 asf_ipsec: Patch to fix the issue of crash in Ping6.
4f60755 asf_ipsec: Patch to add the support of multiple policy mapping to single SA.
b5c14e6 ASF-AH: Take care of padding in ICV of AH Header
98c79ea asf_ipsec: Patch to fix the issue of errors introduced while removing the compilation errors.
31ab748 asf_ipsec: Patch to fix the issue of memory leak for ping6.
0e3836e asfipsec: TCP retransmission fails with IPSec configuration.
efdf28a ASF-IPv6-IPSEC : proper link table creation for IPv6 packets having nr_frags
69fccba ASFIPSEC: Correcting the in_sa and sa_list stats display
6552560 sf_ipsec: Patch to fix the issue of packet drop for > 1360 bytes.
55be89f ASFIPSEC: Added support for NULL XCBC algorithm.
a2a0982 asf_ipsec_qos: Patch to fix the memory leak in IPsec module.
103094e asf_ipsec: Patch to fix the AH IPv6 ping with ESN.
24cde96 ASFIPSEC: Fragment the IPv4 packet if required and send for IPv4-in-IPv6 tunnel.
2c16da6 ASF: setting gianfar_destructor to NULL before sending packet to linux.
9d817d0 asf_ipsec: Patch to add the support to copy DSCP from inner to outer header.
0992f05 IPSEC: fix for fragmentation data buffer corruption.
db18bda IPSEC- Supporting cipher algo AES-CTR, ESP-NULL and
81b20cd asfipsec-enabling seq overflow handling and adding re-keying in overflow case.
c23b1ae IPSEC-supporting PMTU based icmp in Source NAT case.
fd708ce asfipsec-fix the tail stripping for fragmented packets
1887c6d asfipsec-optimizing the mtu length check and l2blob expiry.
76c5d69 Fixed ESP padding in IPsec to be monotonically increasing numbers.
ca74bfa ASF: Removing compilation errors for XTRA Stats
606c594 Adding more functionality in asf_pktdump
80c8fa0 ASF: Supporting Multiple flows in SCTP
2ba1847 ASF: Miscellaneous changes
d27137e ASF: Supporting SCTP traffic in firewall/NAT
82a89e4 ASF: Invalidate all VSG's in asfctrl_invalidate_sessions function
ec6d625 ASF: Added VSG support
df42b23 ASF_V6: Patch to fix crash if first fragmented packet is sent to Linux
63a13e2 ASF: optimization of SG while fragmentation to reuse the first buffer
7718065 ASF: Check the more fragment bit for IPv6 at proper offset
810f173 ASF_FFP: Patch to fix the race condition in case of RT
c9e4edd ASF: dummy functions removal
e63f176 ASF: Making asfGetNode and asfReleaseNode thread safe
3e8e7b3 ASF: Fix for iface_not_found problem when device ifindex > 16
1354c95 ASF_REASMBLY: Modifying IP options only if option header is present
349d6d9 ASF: Change the dummy packet offset
b3ee577 ASF: made old_l2blob_jiffies_timeout user configurable
93c4864 ASF - runtime packet dump support
2471d1d ASF Cleanup - Timer RQ corrections
4180b6e Using IP header Identifcation field from the Head SKB itself.
a82969d ASF_IPv6: Porting the miscellenous changes for IPv6 activity.
61c08a4 ASF STATS - Adding extra stats for Reassembly and Timer
6def023 ASFSTATS - Enhancing the stats printing
3009524 Replacing printk with pr_err, pr_info, pr_warning
1f896bf ASF: Patch to avoid creation of duplicate flows
5862af3 ASF: Patch to add support for ip_options.
4c58c87 ASFIPSEC: Adding proc interface for showing IN/OUT SA list
4398bc9 ASF: Cleanup and reallignement of common global variables
1ebe80c ASFCTRL: Enabling the net MTU change event
7062cec ASF_REASSEM: Allocating fragmentation frame from outer dev
2875982 ASF: Minor enhancements
d41f350 ASF: Setting skb->next to null in asfReasmCleanCb
51d7efa ASF: Defining dimensioning macros at single place
93d673d ASF: updating the the asf reassembly library

Signed-off-by: Ting Liu <ting.liu@freescale.com>